ALTER TABLE "TeamAnnouncement"
    ADD COLUMN IF NOT EXISTS "icon" TEXT;

ALTER TABLE "TeamAnnouncement"
    ADD COLUMN IF NOT EXISTS "title" TEXT;

ALTER TABLE "TeamAnnouncement"
    ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
