// Idempotente seed van kostenposten 2026 januari t/m april uit Excel.
// Bij volgende builds: skip als er voor een maand al posten staan.

import { PrismaClient } from '@prisma/client'

interface CostItem {
  amount: number
  description: string
}

const COSTS: Record<number, CostItem[]> = {
  1: [
    { amount: 28297.78, description: 'ASR Verzuimverzekering' },
    { amount: 225, description: 'Delfts congress support (intervisie cursus)' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 157.3, description: 'Academie voor de Rechtspraak' },
    { amount: 170.64, description: 'Albert Heijn bestelling' },
    { amount: 20.51, description: 'Fietskoerier' },
    { amount: 15.6, description: 'De Bary koffie etc' },
    { amount: 449, description: 'Iside' },
    { amount: 12.99, description: 'Spotify abonnement' },
    { amount: 423.04, description: 'Google Ireland Limited' },
    { amount: 379.98, description: 'Milieuservice' },
    { amount: 36.28, description: 'Milieuservice' },
    { amount: 12.75, description: 'Vlaams Broodhuys' },
    { amount: 125.48, description: 'Viking kantoorspullen' },
    { amount: 65.15, description: 'Viking kantoorspullen' },
    { amount: 17.48, description: 'HEMA cadeau zwangerschap' },
    { amount: 1.39, description: 'HEMA cadeau kaartje' },
    { amount: 10.9, description: 'Rituals zwangerschap cadeau' },
    { amount: 81.5, description: 'Five City Spa zwangerschap' },
    { amount: 19.74, description: 'Viking kantoorspullen' },
    { amount: 106.54, description: 'Albert Heijn bestelling' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 10015.79, description: 'KWPS factuur (door te belasten)' },
    { amount: 136.13, description: 'Stadhouders Advocaten (intervisie)' },
    { amount: 545.11, description: 'Stadhouders factuur (door te belasten)' },
    { amount: 121, description: 'Avocare arbeidsrecht (intervisie)' },
    { amount: 565.9, description: 'NDSM Apotheek (vaccines griep)' },
    { amount: 13123.73, description: 'Herengracht Investments' },
    { amount: 132.32, description: 'Broodjes Zero Zero' },
    { amount: 151.25, description: 'Legal Mike' },
    { amount: 120, description: 'Mickey Philips ???' },
    { amount: 44.45, description: 'PostNL pakketten versturen rechtbank' },
    { amount: 10.5, description: 'Vlaams Broodhuys' },
    { amount: 41.3, description: 'Albert Heijn' },
    { amount: 84, description: 'Bocca Coffee' },
    { amount: 257.23, description: 'Gamma Business (Obidos)' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 108.33, description: 'ABN AMRO servicekosten' },
    { amount: 500, description: 'Google Ireland Limited' },
    { amount: 72.67, description: 'Digihero (belcentrale)' },
    { amount: 6.38, description: 'Albert Heijn' },
    { amount: 369.05, description: 'Declaratie Marnix (kruk)' },
    { amount: 1014.82, description: 'Declaratie Juliette (congres buitenland)' },
    { amount: 2160, description: 'Bright Pensioen' },
    { amount: 909.54, description: 'International Card Services' },
    { amount: 54, description: 'Financieele Dagblad' },
    { amount: 2290.24, description: 'Norm Finance' },
    { amount: 2643.22, description: 'Constant IT' },
    { amount: 13123.73, description: 'Herengracht Investments' },
    { amount: 225, description: 'Delfts congress support (intervisie cursus)' },
    { amount: 97.68, description: 'Froot factuur' },
    { amount: 206.05, description: 'Albert Heijn bestelling' },
    { amount: 101.16, description: 'Froot factuur' },
    { amount: 20.51, description: 'Fietskoerier' },
    { amount: 4.25, description: 'Vlaams Broodhuys' },
    { amount: 1750, description: 'Mooi Boules aanhangborrel' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 645.5, description: 'KPN abonnement' },
    { amount: 8.55, description: 'Kamer van Koophandel' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 38.85, description: 'Cadeau relatie brownie box' },
    { amount: 16.98, description: 'Bol.com kantoorspullen' },
    { amount: 60.5, description: 'Vereniging voor Arbeidsrecht' },
    { amount: 65.4, description: 'De Bary koffie etc' },
    { amount: 902.06, description: 'Spontaanja schoonmaker' },
    { amount: 139, description: 'Ministerie van Justitie (door te belasten)' },
    { amount: 38.5, description: 'Lotte declaratieformulier' },
    { amount: 1329.11, description: 'Basenet abonnement' },
    { amount: 296.97, description: 'Tentoo' },
    { amount: 291.1, description: 'Justine declaratieformulier reiskosten' },
    { amount: 152.68, description: 'Albert Heijn bestelling' },
    { amount: 58.49, description: 'Bol.com kantoorspullen' },
    { amount: 24.39, description: 'Brownie box relatiegeschenken' },
    { amount: 414.4, description: 'Declaratieformulier Marlieke reiskosten' },
  ],
  2: [
    { amount: 4.25, description: 'Vlaams Broodhuys' },
    { amount: 13.03, description: 'Albert Heijn extra' },
    { amount: 79.9, description: 'Bol.com' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 418.33, description: 'Google Ireland Limited incasso' },
    { amount: 12.99, description: 'Spotify abonnement' },
    { amount: 10.45, description: 'Vlaams Broodhuys' },
    { amount: 611, description: 'Schikking Gerardo Bekoba Siale' },
    { amount: 220, description: 'Krua Thai Classic (partnerdiner)' },
    { amount: 34.62, description: 'Albert Heijn extra' },
    { amount: 56.13, description: 'Fleurop bloemen' },
    { amount: 46.12, description: 'Fleurop bloemen' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 785.29, description: 'Norm Finance B.V.' },
    { amount: 210.54, description: 'Constant IT' },
    { amount: 266.2, description: 'TTWWOO' },
    { amount: 181.39, description: 'Albert Heijn bestelling' },
    { amount: 1210, description: 'Van Loman (door te belasten)' },
    { amount: 92.31, description: 'Albert Heijn bestelling' },
    { amount: 526.35, description: 'Stichting Spuistraat 10' },
    { amount: 44.9, description: 'Kamer van Koophandel abonnement' },
    { amount: 449, description: 'Iside' },
    { amount: 80.16, description: 'Stadhouders Advocaten (advies)' },
    { amount: 166.38, description: 'Stadhouders Advocaten (advies)' },
    { amount: 70.35, description: 'DBA (Bary) koffies etc' },
    { amount: 30, description: 'Marie-Stella-Maris (cadeau Juul)' },
    { amount: 108.9, description: 'Bocca Coffee 3x zakken' },
    { amount: 72.83, description: 'Digihero (belcentrale)' },
    { amount: 4.58, description: 'Albert Heijn extra' },
    { amount: 867.33, description: 'Merchlab B.V. (handdoeken lustrum)' },
    { amount: 60.5, description: 'Dutch Arbitration Association (intervisie)' },
    { amount: 740.29, description: 'Norm Finance B.V.' },
    { amount: 151.25, description: 'Legal Mike' },
    { amount: 12, description: 'Kosten buitenlandse overboeking' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 15.98, description: 'Albert Heijn extra' },
    { amount: 7250, description: 'Delft Congress Support (congress)' },
    { amount: 825.5, description: 'Iside' },
    { amount: 14.13, description: 'Albert Heijn extra' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 24.99, description: 'Athenaeum Spui (tijdschriften Emma verlof)' },
    { amount: 67, description: "Marie-Stella-Maris (cadeau Marlieke & Bar?)" },
    { amount: 23.39, description: 'Brownie box relatiegeschenk' },
    { amount: 5.58, description: 'Albert Heijn' },
    { amount: 1500, description: 'International Card Services' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 8.5, description: 'Declaratieformulier Lotte (brood)' },
    { amount: 598.95, description: 'Van Benthem & Keulen advies' },
    { amount: 90.75, description: 'Citius Advocaten intervisie' },
    { amount: 13123.73, description: 'Herengracht Investments huur' },
    { amount: 101.15, description: 'Froot' },
    { amount: 8.99, description: 'Declaratieformulier Lotte' },
    { amount: 226.03, description: 'Albert Heijn bestelling' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 275.28, description: 'HJ Advocaten & Mediators Accenture (doorbelast)' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 48.89, description: 'Viking Netherlands (kantoorspullen)' },
    { amount: 98.07, description: 'ABN AMRO (maandtariferingsnota)' },
    { amount: 3.19, description: 'Albert Heijn extra' },
    { amount: 12, description: 'Kosten buitenlandse overboeking' },
    { amount: 257.23, description: 'Gamma Business Services' },
    { amount: 500, description: 'Google Ireland Limited incasso' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 1393.87, description: 'Basenet abonnement' },
    { amount: 4924.7, description: 'KWPS factuur doorbelast' },
    { amount: 1331, description: 'Constant IT' },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht abonnement' },
    { amount: 968.37, description: 'Declaratieformulier Juliette congres buitenland' },
    { amount: 33.85, description: 'Topgeschenken bloemetje' },
    { amount: 16.1, description: 'Declaratieformulier Erika' },
    { amount: 185.41, description: 'Albert Heijn bestelling' },
    { amount: 125, description: 'Stichting Opleiding Advocaten' },
    { amount: 7.55, description: 'DBA (Bary) koffies etc' },
    { amount: 12.75, description: 'Vlaams Broodhuys' },
    { amount: 1285.39, description: 'Schoonmaker Spontaanja' },
    { amount: 24.99, description: 'Coolblue (filters koffiemachine)' },
    { amount: 503.76, description: 'International Card Services' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 6.38, description: 'Albert Heijn extra' },
    { amount: 22.99, description: 'Bol.com' },
    { amount: 12.75, description: 'Vlaams Broodhuys' },
    { amount: 331.16, description: 'Tentoo' },
    { amount: 77.97, description: 'Smartcoffee (Boonchance)' },
    { amount: 5.49, description: 'HEMA knuffeltje zwangerschap' },
    { amount: 22.99, description: 'Bol.com (boek zonen)' },
    { amount: 775.53, description: 'Proceskosten Yvonne Ruijters' },
    { amount: 29.95, description: 'Abonnement Kamer van Koophandel' },
    { amount: 54, description: 'Financieele Dagblad' },
    { amount: 7210.5, description: 'Creditbetaling Outform facturen (zonder BTW)' },
    { amount: 22.99, description: 'Bol.com (boek zonen)' },
    { amount: 2643.22, description: 'Constant IT' },
  ],
  3: [
    { amount: 34.5, description: 'Vlaams Broodhuys' },
    { amount: 210.69, description: 'Albert Heijn bestelling' },
    { amount: 449, description: 'Iside' },
    { amount: 639.45, description: 'KPN abonnementen' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 178.35, description: 'Norm Finance abonnement' },
    { amount: 3.19, description: 'Albert Heijn extra' },
    { amount: 427.55, description: 'Google Ireland Limited' },
    { amount: 12.99, description: 'Spotify abonnement' },
    { amount: 12, description: 'Vlaams Broodhuys' },
    { amount: 99.19, description: 'Viking kantoorspullen' },
    { amount: 899.31, description: 'De Lage Landen Vendorlease (printer)' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 23.98, description: 'Bol.com' },
    { amount: 8.65, description: 'Albert Heijn extra' },
    { amount: 42.13, description: 'Fleurop bloemen Bar operatie' },
    { amount: 151.25, description: 'Legal Mike' },
    { amount: 6.38, description: 'Albert Heijn extra' },
    { amount: 6.19, description: 'Albert Heijn extra' },
    { amount: 72.93, description: 'Digihero B.V. (belcentrale)' },
    { amount: 50.94, description: 'PCI reparatie kantoor (printer)' },
    { amount: 12, description: 'Vlaams Broodhuys' },
    { amount: 75, description: 'Amstelveld aanbetaling borrel Workx' },
    { amount: 8.5, description: 'Vlaams Broodhuys' },
    { amount: 208.73, description: 'TTWWOO' },
    { amount: 101.44, description: 'Declaratieformulier Wies' },
    { amount: 5313.42, description: 'KWPS factuur (doorbelast)' },
    { amount: 127.05, description: 'Constant IT vragen Exact' },
    { amount: 581, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 1162, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 16.35, description: 'DBA (Bary) koffies etc.' },
    { amount: 49.75, description: 'Declaratieformulier Marnix' },
    { amount: 193.62, description: 'Albert Heijn bestelling' },
    { amount: 291, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 225, description: 'Delfts congress support' },
    { amount: 1394.16, description: 'Basenet abonnement' },
    { amount: 362.92, description: 'Aanpassing huur' },
    { amount: 1744, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 225, description: 'Delfts congress support' },
    { amount: 101.15, description: 'Froot' },
    { amount: 121, description: 'Youman Fisher intervisie' },
    { amount: 291, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 2713.43, description: 'HJ Advocaten & Mediators (doorbelast)' },
    { amount: 291, description: 'Contributie Nederlandse Orde van Advocaten' },
    { amount: 182.85, description: 'Albert Heijn bestelling' },
    { amount: 382.16, description: 'Declaratieformulier Julia reiskosten' },
    { amount: 529.07, description: 'Stadhouders Advocaten' },
    { amount: 726, description: "Bram Willems Photography (foto's Alexander etc)" },
    { amount: 344.85, description: 'Vereniging Arbeidsrecht deelname' },
    { amount: 302.5, description: 'Vereniging Arbeidsrecht deelname' },
    { amount: 135, description: 'Partner lunch bij Buffet van Odette' },
    { amount: 4.28, description: 'Albert Heijn extra' },
    { amount: 257.23, description: 'Gamma Business Services' },
    { amount: 9.94, description: 'Bol.com' },
    { amount: 4.25, description: 'Vlaams Broodhuys' },
    { amount: 4.52, description: 'Albert Heijn extra' },
    { amount: 225, description: 'Declaratieformulier Juliette' },
    { amount: 9.48, description: 'Albert Heijn extra' },
    { amount: 3.58, description: 'Albert Heijn extra' },
    { amount: 500, description: 'Google Ireland Limited' },
    { amount: 12, description: 'Vlaams Broodhuys' },
    { amount: 26627.42, description: 'Constant IT' },
    { amount: 229.64, description: 'Declaratieformulier Justine reiskosten' },
    { amount: 68.47, description: 'Viking kantoorspullen' },
    { amount: 178.27, description: 'Albert Heijn bestelling' },
    { amount: 2269.35, description: 'Nectaro B.V. (Lodewijk)' },
    { amount: 500, description: 'Declaratieformulier Erika' },
    { amount: 806.65, description: 'International Card Services' },
    { amount: 9.1, description: 'Vlaams Broodhuys' },
    { amount: 11.45, description: 'DBA (Bary) koffies etc.' },
    { amount: 4.25, description: 'Declaratieformulier Hanna (brood)' },
    { amount: 4043.81, description: 'Chambers betaling' },
    { amount: 147.06, description: 'Declaratieformulier Marlieke reiskosten' },
    { amount: 9.1, description: 'Vlaams Broodhuys' },
    { amount: 595.32, description: 'Doxflow abonnement' },
    { amount: 227.29, description: 'Vurich gerechtsdeurwaarder' },
    { amount: 181.5, description: 'Nepbloemen kantoor' },
    { amount: 12.95, description: 'Vlaams Broodhuys' },
    { amount: 902.06, description: 'Spontaanja schoonmaker' },
    { amount: 331.16, description: 'Tentoo' },
    { amount: 1.09, description: 'Albert Heijn' },
    { amount: 77.97, description: 'Smartcoffee (Boonchance)' },
    { amount: 141.39, description: 'ABN AMRO maandtariferingsnota' },
    { amount: 54, description: 'Financieele Dagblad abonnement' },
    { amount: 225, description: 'Delfts congress support' },
    { amount: 7.6, description: 'Albert Heijn extra' },
    { amount: 24.19, description: 'Adobe Pro account Workx' },
    { amount: 615.25, description: 'KPN abonnementen' },
    { amount: 37.1, description: 'Kamer van Koophandel abonnement' },
    { amount: 12.95, description: 'Vlaams Broodhuys' },
    { amount: 69.48, description: 'NS Reizigers' },
    { amount: 7.67, description: 'Albert Heijn extra' },
  ],
  4: [
    { amount: 7.27, description: 'Albert Heijn extra' },
    { amount: 657.57, description: 'Merchado B.V. (flessen Mallorca lustrum)' },
    { amount: 38.48, description: 'Albert Heijn extra' },
    { amount: 4.4, description: 'PostNL koerierdiensten' },
    { amount: 8.57, description: 'Albert Heijn extra' },
    { amount: 12.95, description: 'Vlaams Broodhuys' },
    { amount: 86.32, description: 'Zerozero broodjes lunch' },
    { amount: 52.1, description: 'Albert Heijn extra' },
    { amount: 30.25, description: 'Fax systeem op printer' },
    { amount: 55, description: 'Jonge Balie Amsterdam' },
    { amount: 55, description: 'Jonge Balie Amsterdam' },
    { amount: 55, description: 'Jonge Balie Amsterdam' },
    { amount: 27.5, description: 'Jonge Balie Amsterdam' },
    { amount: 27.5, description: 'Jonge Balie Amsterdam' },
    { amount: 449, description: 'Iside' },
    { amount: 247.5, description: 'Iside' },
    { amount: 600, description: 'Iside' },
    { amount: 12.99, description: 'Spotify' },
    { amount: 37.88, description: 'Albert Heijn extra' },
    { amount: 407.07, description: 'Google Ireland Limited' },
    { amount: 31.68, description: 'Albert Heijn extra' },
    { amount: 3, description: 'Albert Heijn extra' },
    { amount: 181.85, description: 'Viking kantoorspullen' },
    { amount: 31.95, description: 'Boekenbon cadeau Barbara' },
    { amount: 23.35, description: 'Albert Heijn extra' },
    { amount: 9077.42, description: 'Nectaro B.V. (Lodewijk)' },
    { amount: 815, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 815, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 380, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 286.7, description: 'DBA (Bary) + huur zaaltje' },
    { amount: 7865, description: 'Stichting IDFA (partnership)' },
    { amount: 650, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 50, description: 'Zerozero broodjes lunch' },
    { amount: 84.7, description: 'Mediationgenootschap.nl' },
    { amount: 3645.49, description: 'ALO (Partners in Mediation)' },
    { amount: 2132.29, description: 'ALO (Partners in Mediation)' },
    { amount: 250, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 380, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 815, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 1402.58, description: 'Basenet abonnement' },
    { amount: 13.65, description: 'Vlaams Broodhuys' },
    { amount: 650, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 380, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 380, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 250, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 13562.98, description: 'Herengracht Investments (huur)' },
    { amount: 2765.17, description: 'Norm Finance' },
    { amount: 2.49, description: 'Albert Heijn extra' },
    { amount: 40.46, description: 'Mailonderzoek Basenet Marnix' },
    { amount: 227.64, description: 'Albert Heijn bestelling' },
    { amount: 28.95, description: 'Bol.com' },
    { amount: 192, description: 'Vurich gerechtsdeurwaarders' },
    { amount: 121.32, description: 'Zerozero broodjes lunch' },
    { amount: 210.73, description: 'Albert Heijn bestelling' },
    { amount: 20.95, description: 'Nijntje knuffel cadeau Justine' },
    { amount: 101.15, description: 'Froot' },
    { amount: 6.38, description: 'Albert Heijn' },
    { amount: 62.93, description: 'Cadeau Alain' },
    { amount: 154.82, description: 'Declaratieformulier Justine reiskosten' },
    { amount: 6.28, description: 'Albert Heijn extra' },
    { amount: 25.08, description: 'Bol.com' },
    { amount: 565.1, description: 'Fiets Workx Julia' },
    { amount: 257.23, description: 'Gamma Business Services' },
    { amount: 1162, description: 'Nederlandse Orde van Advocaten' },
    { amount: 815, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 169.4, description: 'Intervisie PiP Advocatuur' },
    { amount: 1162, description: 'Nederlandse Orde van Advocaten' },
    { amount: 1744, description: 'Nederlandse Orde van Advocaten' },
    { amount: 1162, description: 'Nederlandse Orde van Advocaten' },
    { amount: 815, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 581, description: 'Nederlandse Orde van Advocaten' },
    { amount: 121, description: 'Pallas Advocaten intervisie' },
    { amount: 270, description: 'Hotel Arena (partner borrel)' },
    { amount: 9.1, description: 'Vlaams Broodhuys' },
    { amount: 44.27, description: 'Viking kantoorspullen' },
    { amount: 260.48, description: 'Albert Heijn bestelling' },
    { amount: 581, description: 'Nederlandse Orde van Advocaten' },
    { amount: 250, description: 'Amsterdamse Orde van Advocaten' },
    { amount: 2627.42, description: 'Constant IT' },
    { amount: 1162, description: 'Nederlandse Orde van Advocaten' },
    { amount: 529.6, description: 'Fiets Workx Lotte' },
    { amount: 88.35, description: 'DBA (Bary) + huur zaaltje' },
    { amount: 500, description: 'Google Ireland Limited' },
    { amount: 72.67, description: 'Digihero' },
    { amount: 5.78, description: 'Albert Heijn extra' },
    { amount: 22, description: 'PostNL koerierdiensten' },
    { amount: 753.31, description: 'International Card Services' },
    { amount: 114.32, description: 'Declaratieformulier Maaike' },
    { amount: 24285.64, description: 'Waarborgsom Herengracht Investments huur' },
    { amount: 581, description: 'Nederlandse Orde van Advocaten' },
    { amount: 129.95, description: 'Smartcoffee (Boonchance)' },
    { amount: 54, description: 'Financieele Dagblad' },
    { amount: 4.55, description: 'Vlaams Broodhuys' },
    { amount: 1804.37, description: 'KPN factuur' },
    { amount: 902.06, description: 'Spontaanja schoonmaker' },
    { amount: 80, description: 'Marleenkookt (cadeaubon bevalling Wies)' },
    { amount: 4.55, description: 'Vlaams Broodhuys' },
    { amount: 2.69, description: 'Albert Heijn extra' },
  ],
}

export async function main() {
  if (!process.env.DATABASE_URL) {
    console.log('[seed-monthly-costs] geen DATABASE_URL — overslaan')
    return
  }
  const prisma = new PrismaClient()
  try {
    let added = 0
    let skipped = 0
    for (const [monthStr, items] of Object.entries(COSTS)) {
      const month = parseInt(monthStr, 10)
      const existing = await prisma.monthlyCost.count({ where: { year: 2026, month } })
      if (existing > 0) {
        skipped += items.length
        continue
      }
      await prisma.monthlyCost.createMany({
        data: items.map((it, i) => ({
          year: 2026,
          month,
          amount: it.amount,
          description: it.description,
          sortOrder: i,
        })),
      })
      added += items.length
    }
    console.log(`[seed-monthly-costs] ${added} posten toegevoegd, ${skipped} overgeslagen`)
  } catch (err) {
    console.error('[seed-monthly-costs] mislukt (build gaat door):', err)
  } finally {
    await prisma.$disconnect().catch(() => {})
  }
}

if (require.main === module) main()